# High-level wear-leveling benchmarks


# these are common and can be overridden suite-wide
#
# note for bench_*_many, file size defaults to CHUNK, and SIZE = sum of
# all files
#
defines.SIZE = '1024*1024' # 1 MiB
defines.CHUNK = 64
defines.SEED = 42

# we probably want a smaller disk for this test
defines.DISK_SIZE = '8*1024*1024' # 8 MiB

# simulated time, in nanoseconds, to run the test
#
# you probably _don't_ want this for wear-leveling!
defines.SIM_TIME = 0 # '60ULL*60ULL*1000ULL*1000ULL*1000ULL' # 1 hour
# simulation size in bytes
defines.SIM_SIZE = '100*DISK_SIZE'

# set this to true to skip bench warmup
defines.SKIP_WARMUP = false

# optionally create a bunch of static files
defines.STATIC_COUNT = 0
defines.STATIC_SIZE = 'BLOCK_SIZE' # not inlined
defines.STATIC_COMPACT = false

if = [
    # spiffs is limited to 32-bit disks
    'BENCH_IFDEF_SPIFFS(DISK_SIZE < 0x100000000ULL, true)',
    # both spiffs/yaffs2 need a spare page for bookkeeping
    'BENCH_IFDEF_SPIFFS(BLOCK_SIZE > SPAGE_SIZE, true)',
    'BENCH_IFDEF_YAFFS2(BLOCK_SIZE > YPAGE_SIZE, true)',
]

hooks.init = 'bench_wear_init'
hooks.deinit = 'bench_wear_deinit'
hooks.erase = 'bench_wear_bd_erase'
code = '''
    // include common bench helpers
    #include "benches/bench_helpers.h"

    // needed for sqrt
    #include <math.h>

    // measure wear
    bench_io_t *bench_wear_erasemap;

    // init bench state
    void bench_wear_init(void) {
        BENCH_HEAP_PAUSE();
        bench_wear_erasemap = malloc(BLOCK_COUNT*sizeof(bench_io_t));
        memset(bench_wear_erasemap, 0, BLOCK_COUNT*sizeof(bench_io_t));
        BENCH_HEAP_RESUME();
    }

    // cleanup bench state
    void bench_wear_deinit(void) {
        BENCH_HEAP_PAUSE();
        free(bench_wear_erasemap);
        BENCH_HEAP_RESUME();
    }

    // reset after warmup
    void bench_wear_reset(void) {
        memset(bench_wear_erasemap, 0, BLOCK_COUNT*sizeof(bench_io_t));
    }

    // hook erase
    int bench_wear_bd_erase(const struct lfs3_cfg *cfg, lfs3_block_t block) {
        bench_wear_erasemap[block] += 1;
        return BENCH_BD_ERASENOHOOKS(cfg, block);
    }

    // some interesting stats

    // wear-amplification factor, i.e.
    // sum(erases)*BLOCK_SIZE/written
    double bench_wear_waf(bench_io_t written) {
        if (!bench_wear_erasemap) {
            return 0.0;
        }

        bench_io_t wear_sum = 0;
        for (lfs3_block_t i = 0; i < BLOCK_COUNT; i++) {
            wear_sum += bench_wear_erasemap[i];
        }
        return ((double)wear_sum*(double)BLOCK_SIZE)
                / (double)((written) ? written : 1);
    }

    // conservative wear-amplification factor, i.e.
    // (max(erases)*BLOCK_COUNT*BLOCK_SIZE)/written
    double bench_wear_cwaf(bench_io_t written) {
        if (!bench_wear_erasemap) {
            return 0.0;
        }

        bench_io_t wear_max = 0;
        for (lfs3_block_t i = 0; i < BLOCK_COUNT; i++) {
            if (bench_wear_erasemap[i] > wear_max) {
                wear_max = bench_wear_erasemap[i];
            }
        }
        return ((double)wear_max*(double)BLOCK_COUNT*(double)BLOCK_SIZE)
                / (double)((written) ? written : 1);
    }
'''


# logging write throughput
#
# two big differences from seq:
# 1. fruncate/rotations instead of rewind+truncate
# 2. sync called on every write
[cases.bench_wear_logging]
defines.FRUNCATE = false
code = '''
    #if defined(LFS3)
    lfs3_t lfs3;
    lfs3_format(&lfs3, LFS3_F_RDWR, CFG) => 0;
    lfs3_mount(&lfs3, LFS3_M_RDWR | LFS3_M_MKCONSISTENT, CFG) => 0;
    #elif defined(LFS2)
    lfs2_t lfs2;
    lfs2_format(&lfs2, CFG_LFS2) => 0;
    lfs2_mount(&lfs2, CFG_LFS2) => 0;
    lfs2_fs_mkconsistent(&lfs2) => 0;
    #elif defined(SPIFFS)
    spiffs spiffs;
    spiffs.user_data = CFG;
    uint8_t *work_buffer = malloc(2*SPAGE_SIZE);
    uint8_t *fd_buffer = malloc(FD_SIZE);
    uint8_t *scache_buffer = malloc(SCACHE_SIZE);
    // spiffs format without magic just needs a disk erase
    SPIFFS_mount(&spiffs, (spiffs_config*)CFG_SPIFFS, work_buffer,
            fd_buffer, FD_SIZE,
            scache_buffer, SCACHE_SIZE,
            NULL) => 0;
    #elif defined(YAFFS2)
    // note this implicitly zeros yaffs_dev
    struct yaffs_dev yaffs2 = {
        .driver_context = CFG,
        .param = CFG_YAFFS2->param,
        .drv = CFG_YAFFS2->drv,
    };
    yaffs_add_device(&yaffs2);
    yaffs_format("/", false, false, false) => 0;
    yaffs_mount("/") => 0;
    #endif
    if (!SKIP_WARMUP) {
        BENCH_STACK_PAUSE();
        BENCH_HEAP_PAUSE();
        #if defined(LFS3)
        int err = bench_helpers_warmup(CFG, &lfs3);
        #elif defined(LFS2)
        int err = bench_helpers_warmup(CFG, &lfs2);
        #elif defined(SPIFFS)
        int err = bench_helpers_warmup(CFG, &spiffs);
        #elif defined(YAFFS2)
        int err = bench_helpers_warmup(CFG, &yaffs2);
        #endif
        if (err) {
            LFS3_ERROR("Bench warmup failed: %d", err);
            assert(!err);
            return;
        }
        BENCH_HEAP_RESUME();
        BENCH_STACK_RESUME();
    }
    if (STATIC_COUNT) {
        BENCH_STACK_PAUSE();
        BENCH_HEAP_PAUSE();
        #if defined(LFS3)
        int err = bench_helpers_populate(CFG, &lfs3,
                STATIC_COUNT, STATIC_SIZE, STATIC_COMPACT);
        #elif defined(LFS2)
        int err = bench_helpers_populate(CFG, &lfs2,
                STATIC_COUNT, STATIC_SIZE, STATIC_COMPACT);
        #elif defined(SPIFFS)
        int err = bench_helpers_populate(CFG, &spiffs,
                STATIC_COUNT, STATIC_SIZE, STATIC_COMPACT);
        #elif defined(YAFFS2)
        int err = bench_helpers_populate(CFG, &yaffs2,
                STATIC_COUNT, STATIC_SIZE, STATIC_COMPACT);
        #endif
        if (err) {
            LFS3_ERROR("Bench populate failed: %d", err);
            assert(!err);
            return;
        }
        BENCH_HEAP_RESUME();
        BENCH_STACK_RESUME();
    }
    uint32_t prng = SEED;
    uint8_t *wbuf = malloc(CHUNK);

    // reset our timer
    BENCH_SIMRESET();
    // and our wear
    bench_wear_reset();

    // open a file
    #if defined(LFS3)
    lfs3_file_t file;
    lfs3_file_open(&lfs3, &file, "bench_log",
            LFS3_O_WRONLY | LFS3_O_CREAT | LFS3_O_EXCL | LFS3_O_APPEND) => 0;
    #elif defined(LFS2)
    lfs2_file_t file;
    lfs2_file_open(&lfs2, &file, "bench_log",
            LFS2_O_WRONLY | LFS2_O_CREAT | LFS2_O_EXCL | LFS2_O_APPEND) => 0;
    #elif defined(SPIFFS)
    spiffs_file fd = SPIFFS_open(&spiffs, "bench_log",
            SPIFFS_WRONLY | SPIFFS_CREAT | SPIFFS_EXCL | SPIFFS_APPEND, 0777);
    assert(fd >= 0);
    #elif defined(YAFFS2)
    int fd = yaffs_open("bench_log",
            O_WRONLY | O_CREAT | O_EXCL | O_APPEND, 0777);
    assert(fd >= 0);
    #endif
    uint64_t written = 0;
    // ok, one of these needs to be non-zero
    LFS3_ASSERT(SIM_TIME > 0 || SIM_SIZE > 0);
    while ((SIM_SIZE && written < (uint64_t)SIM_SIZE)
            || (SIM_TIME && BENCH_SIMTIME() < SIM_TIME)) {
        BENCH_START("write");
        // append to log
        for (lfs3_size_t j = 0; j < CHUNK; j++) {
            wbuf[j] = 'a' + (BENCH_PRNG(&prng) % 26);
        }
        #if defined(LFS3)
        lfs3_file_write(&lfs3, &file, wbuf, CHUNK) => CHUNK;
        #elif defined(LFS2)
        lfs2_file_write(&lfs2, &file, wbuf, CHUNK) => CHUNK;
        #elif defined(SPIFFS)
        SPIFFS_write(&spiffs, fd, wbuf, CHUNK) => CHUNK;
        #elif defined(YAFFS2)
        yaffs_write(fd, wbuf, CHUNK) => CHUNK;
        #endif

        // sync
        #if defined(LFS3)
        lfs3_file_sync(&lfs3, &file) => 0;
        #elif defined(LFS2)
        lfs2_file_sync(&lfs2, &file) => 0;
        #elif defined(SPIFFS)
        s32_t d = SPIFFS_fflush(&spiffs, fd);
        assert(d >= 0);
        #elif defined(YAFFS2)
        yaffs_fsync(fd) => 0;
        #endif

        // for v3, fruncate, for v2, rotate if full
        //
        // unlike litmus benchmarks we just use SIZE here
        #if defined(LFS3)
        lfs3_soff_t size = lfs3_file_size(&lfs3, &file);
        assert(size >= 0);
        if (FRUNCATE) {
            if (size > SIZE) {
                lfs3_file_fruncate(&lfs3, &file, SIZE) => 0;
            }
        } else {
            if (size >= SIZE) {
                lfs3_file_close(&lfs3, &file) => 0;
                lfs3_rename(&lfs3, "bench_log", "bench_log.1") => 0;
                lfs3_file_open(&lfs3, &file, "bench_log",
                        LFS3_O_WRONLY
                            | LFS3_O_CREAT
                            | LFS3_O_EXCL
                            | LFS3_O_APPEND) => 0;
            }
        }
        #elif defined(LFS2)
        lfs3_soff_t size = lfs2_file_size(&lfs2, &file);
        assert(size >= 0);
        if (size >= SIZE) {
            lfs2_file_close(&lfs2, &file) => 0;
            lfs2_rename(&lfs2, "bench_log", "bench_log.1") => 0;
            lfs2_file_open(&lfs2, &file, "bench_log",
                    LFS2_O_WRONLY
                        | LFS2_O_CREAT
                        | LFS2_O_EXCL
                        | LFS2_O_APPEND) => 0;
        }
        #elif defined(SPIFFS)
        spiffs_stat stat;
        SPIFFS_fstat(&spiffs, fd, &stat) => 0;
        assert(stat.size >= 0);
        if (stat.size >= SIZE) {
            SPIFFS_close(&spiffs, fd) => 0;
            int err = SPIFFS_remove(&spiffs, "bench_log.1");
            assert(!err || err == SPIFFS_ERR_NOT_FOUND);
            SPIFFS_rename(&spiffs, "bench_log", "bench_log.1") => 0;
            fd = SPIFFS_open(&spiffs, "bench_log",
                    SPIFFS_WRONLY
                        | SPIFFS_CREAT
                        | SPIFFS_EXCL
                        | SPIFFS_APPEND, 0777);
            assert(fd >= 0);
        }
        #elif defined(YAFFS2)
        struct yaffs_stat stat;
        yaffs_fstat(fd, &stat) => 0;
        if (stat.st_size >= SIZE) {
            yaffs_close(fd) => 0;
            yaffs_rename("bench_log", "bench_log.1") => 0;
            fd = yaffs_open("bench_log",
                    O_WRONLY | O_CREAT | O_EXCL | O_APPEND, 0777);
            assert(fd >= 0);
        }
        #endif

        written += CHUNK;
        BENCH_STOP("write", written);
    }
    #if defined(LFS3)
    lfs3_file_close(&lfs3, &file) => 0;
    #elif defined(LFS2)
    lfs2_file_close(&lfs2, &file) => 0;
    #elif defined(SPIFFS)
    SPIFFS_close(&spiffs, fd) => 0;
    #elif defined(YAFFS2)
    yaffs_close(fd) => 0;
    #endif

    // report the resulting wear
    //
    // by default this is summed, but the bench runner has flags to get
    // more interesting information:
    // - -Swear     - get summed erases (the default)
    // - -Swear=cdf - get per-block erases with percentiles
    // - -Swear=p90 - get 90th percentile erases
    // - -Swear=max - get worst case erases
    for (lfs3_block_t i = 0; i < BLOCK_COUNT; i++) {
        BENCH_RESULT("wear", i, bench_wear_erasemap[i]);
    }

    // calculate a few other interesting stats

    // wear-amplification factor, i.e.
    // sum(erases)*BLOCK_SIZE/written
    BENCH_FRESULT("waf", BLOCK_COUNT, bench_wear_waf(written));
    // conservative wear-amplification factor, i.e.
    // (max(erases)*BLOCK_COUNT*BLOCK_SIZE)/written
    BENCH_FRESULT("cwaf", BLOCK_COUNT, bench_wear_cwaf(written));

    // report the total stack/heap usage after the benchmark
    #ifdef BENCH_STACK
    BENCH_RESULT("stack", written, BENCH_STACK_WATERMARK());
    BENCH_RESULT("ctx", written, BENCH_STACK_CURRENT());
    #endif
    #ifdef BENCH_HEAP
    BENCH_RESULT("heap", written, BENCH_HEAP_WATERMARK());
    BENCH_RESULT("buf", written, CHUNK + BUF_WATERMARK);
    #endif

    // find the total disk usage after the benchmark
    struct bench_helpers_usage usage;
    #if defined(LFS3)
    bench_helpers_usage(CFG, &lfs3, &usage) => 0;
    #elif defined(LFS2)
    bench_helpers_usage(CFG, &lfs2, &usage) => 0;
    #elif defined(SPIFFS)
    bench_helpers_usage(CFG, &spiffs, &usage) => 0;
    #elif defined(YAFFS2)
    bench_helpers_usage(CFG, &yaffs2, &usage) => 0;
    #endif
    BENCH_RESULT("usage", written, usage.usage);
    BENCH_RESULT("mdir", written, usage.mdir);
    BENCH_RESULT("btree", written, usage.btree);
    BENCH_RESULT("data", written, usage.data);

    #if defined(LFS3)
    lfs3_unmount(&lfs3) => 0;
    #elif defined(LFS2)
    lfs2_unmount(&lfs2) => 0;
    #elif defined(SPIFFS)
    SPIFFS_unmount(&spiffs);
    free(work_buffer);
    free(fd_buffer);
    free(scache_buffer);
    #elif defined(YAFFS2)
    yaffs_unmount("/") => 0;
    yaffs_remove_device(&yaffs2);
    #endif
    free(wbuf);
'''

